### ISSUE TITLE
Should keep `@vaadin/` scope prefix in package.json names

### ISSUE THREAD

**Issue by platosha** [vaadin/magi-cli#25]
Removing the prefixes from package.json makes essentially unreleasable output.

Because of https://github.com/vaadin/magi-cli/pull/24 manual changes are required to bring the scope name back to be able to make a P3 component release. Having manual steps in releasing process complicates maintenance quite a bit.

**Comment by manolo** [comment]
True, that is because conversion rewrites package.json with the modified info. Fixing it
