### ISSUE TITLE
Release: should install npm dependencies before bumping version

### ISSUE THREAD

**Issue by limonte** [vaadin/magi-cli#42]
![image](https://user-images.githubusercontent.com/6059356/44258479-b20dda80-a217-11e8-943c-f07a9fe9e3e4.png)

**Comment by manolo** [comment]
This was already discussed with @platosha that magi shouldn't modify your workspace. Only p3-convert command updates bower because it's necessary for the process.
But it might be useful if magi does `npm up` as well @platosha wdyt?

**Comment by platosha** [comment]
`npm version` itself does not install or update any dependencies.

I think, it is completely fine to fail in this case if `npm version` fails. It is an early fail, it’s the first step in the release process, should not produce any incomplete releases.

BTW It is rather bad that our `npm version` depends on gulp and third-party dependencies, and we should totally fix that. But making arbitrary fixes for our npm config in `magi-cli` is not a good way either.

**Comment by tomivirkki** [comment]
Closing the original issue as wontfix. `npm version` also no longer depends on `gulp` (but magi-cli)
