### ISSUE TITLE
Unable to enter bender credentials

### ISSUE THREAD

**Issue by limonte** [vaadin/magi-cli#44]
![image](https://user-images.githubusercontent.com/6059356/44259885-7ffe7780-a21b-11e8-84e4-8cf1706ea131.png)

After I enter my Bender username and hit <kbd>Enter</kbd> cursor is moving to the next line and the release script stuck.

**Comment by manolo** [comment]
Release script does not ask for credentials, it just chain a set of steps, calling other scripts.

Individual scripts has the responsibility to set your configuration, hence in this case you need to run `magi deploy --auth` just once in your system

**Comment by limonte** [comment]
Roger 👍

**Comment by platosha** [comment]
> Release script does not ask for credentials, it just chain a set of steps, calling other scripts.

That’s somewhat inconvenient. Should we pipe the user input to the subscripts?
