### ISSUE TITLE
Unpredicted deployment of the component with error.

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/magi-cli#52]
During the release process the error has occurred and shown this message:
![screen shot 2018-08-23 at 11 14 33](https://user-images.githubusercontent.com/29372419/44513571-5daaa500-a6c6-11e8-9cbb-3d1d2487e043.png)
However, the version was still deployed to CDN:
https://cdn-origin.vaadin.com/vaadin-overlay/3.2.0-alpha1/demo/

**Comment by manolo** [comment]
In which point did it fail? deploying to CDN ?

**Comment by limonte** [comment]
Not an issue of `magi`, I deployed `3.2.0-alpha1` to CDN manually because the release with CDN links was there. In order to prevent caching issues, deploy to CDN should be done _before_ making a release.

**Comment by limonte** [comment]
Closing this in favor of #53
