### ISSUE TITLE
Skip or override auto dist-tag on release?

### ISSUE THREAD

**Issue by platosha** [vaadin/magi-cli#61]
I suspect that we might experience the `next` jumping back-and-forth in case if we have both beta and alpha releases during same time. Same with the `latest` if we maintain a couple of stable feature branches, for example...

Maybe add a command line argument to allow for overriding this auto tag with something else or even turn dist-tag off for a particular release?

**Comment by web-padawan** [comment]
> Same with the latest if we maintain a couple of stable feature branches, for example...

Now it strikes back quite a lot. We need to only set `latest` if there is no newer stable release.
